Hw 2 count_det
andrewponomarev/made-cpp-2020-hw pull request #2
Opened 2020-09-27 13:35 UTC by andrewponomarev

2020-10-01 10:34 UTC, SweetWeakness requested changes

2020-10-01 10:34 UTC, SweetWeakness commented on count_det/src/main.s
> +    mov r6, #1
нужен пуш и поп r4-r7

2020-10-01 10:34 UTC, SweetWeakness commented on count_det/src/main.s
> +    ldr r7, [r0], #4
может быть ldrsb?

2020-10-04 21:49 UTC, andrewponomarev commented on count_det/src/main.s
> +    mov r6, #1
исправлено

2020-10-04 21:50 UTC, andrewponomarev commented on count_det/src/main.s
> +    ldr r7, [r0], #4
исправлено

2020-10-29 02:26 UTC, merged