Proj 1 vector operations
andrewponomarev/made-cpp-2020-hw pull request #4
Opened 2020-10-06 18:27 UTC by andrewponomarev

2020-10-17 23:11 UTC, xterrafunny requested changes

2020-10-17 23:11 UTC, xterrafunny commented on vector_operations/src/vector_ops.h
> +    std::vector<double> operator+ (const std::vector<double> &a, const std::vector<double> &b) {
Отступ в 2 пробела

2020-10-17 23:11 UTC, xterrafunny commented on vector_operations/src/vector_ops.h
> +    std::vector<double> operator+ (const std::vector<double> &a, const std::vector<double> &b) {
Пробел перед списком аргументов не нужен

2020-10-17 23:11 UTC, xterrafunny commented on vector_operations/src/vector_ops.h
> +        std::vector<double> c;
Размер вектора заранее известен, зачем заставлять его расширяться через `push_back`

2020-10-17 23:11 UTC, xterrafunny commented on vector_operations/src/vector_ops.h
> +        for (auto i = 0; i < a.size(); ++i){
Зачем здесь `auto`

2020-10-17 23:11 UTC, xterrafunny commented on vector_operations/src/vector_ops.h
> +        double n = a[0] / b[0];
А если `b[0] == 0`

2020-10-18 20:02 UTC, andrewponomarev commented on vector_operations/src/vector_ops.h
> +    std::vector<double> operator+ (const std::vector<double> &a, const std::vector<double> &b) {
Done

2020-10-18 20:02 UTC, andrewponomarev commented on vector_operations/src/vector_ops.h
> +    std::vector<double> operator+ (const std::vector<double> &a, const std::vector<double> &b) {
Done

2020-10-18 20:03 UTC, andrewponomarev commented on vector_operations/src/vector_ops.h
> +        std::vector<double> c;
Done

2020-10-18 20:03 UTC, andrewponomarev commented on vector_operations/src/vector_ops.h
> +        for (auto i = 0; i < a.size(); ++i){
Done

2020-10-18 20:03 UTC, andrewponomarev commented on vector_operations/src/vector_ops.h
> +        double n = a[0] / b[0];
Done

2020-10-29 02:18 UTC, merged